### ISSUE TITLE
Treat modifiers as modifiers and not keys

### ISSUE THREAD

**Issue by johanhelsing** [Leafwing-Studios/leafwing_input_manager#72] opened 2022-02-12 19:41 UTC
## What problem does this solve?

Detect Ctrl+F, but not F+Ctrl

## What solution would you like?

Perhaps something like this?

```rust
input_map.insert_with_modifiers(Find, [LControl, LAlt], F);
```

## Related work

Chords are similar, but they trigger when F is held first and then Ctrl is tapped.

**Comment by alice-i-cecile** [comment] 2022-03-02 21:04
Yep, this is the feature I've been calling "arpeggios".

**Comment by alice-i-cecile** [comment] 2022-03-03 01:41
Closing as a duplicate of #49.

**Closed by alice-i-cecile** 2022-03-03 01:41 UTC
Labels: enhancement
